"""Changed Field name in author column book

Revision ID: 1d50d6070d8c
Revises: 4fb34feb63d1
Create Date: 2023-08-01 17:41:10.414411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d50d6070d8c'
down_revision = '4fb34feb63d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
