"""Deleted Post TO LIBRARY from book

Revision ID: 3558b8263d4e
Revises: 0dea1459cf3f
Create Date: 2023-08-02 18:21:19.128784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3558b8263d4e'
down_revision = '0dea1459cf3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'posted_to_library')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('posted_to_library', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
