"""Added Unique Constrants1

Revision ID: 3a875dd6816c
Revises: c800bef56afa
Create Date: 2023-08-03 14:28:27.471448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a875dd6816c'
down_revision = 'c800bef56afa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_role_uc', 'user_role', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_role_uc', 'user_role', type_='unique')
    # ### end Alembic commands ###
