""" Changed default=borrower 

Revision ID: 4cffede58c20
Revises: 3a875dd6816c
Create Date: 2023-08-04 15:30:37.507852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cffede58c20'
down_revision = '3a875dd6816c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
