"""Added posted_column

Revision ID: 4fb34feb63d1
Revises: f444339ee1c5
Create Date: 2023-08-01 17:19:31.466174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb34feb63d1'
down_revision = 'f444339ee1c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('posted_to_library', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'posted_to_library')
    # ### end Alembic commands ###
