"""Changed in  Books

Revision ID: 79901bbc06ea
Revises: 825353b2552c
Create Date: 2023-08-01 17:54:18.365593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79901bbc06ea'
down_revision = '825353b2552c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('books_author_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_column('books', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_author_fkey', 'books', 'users', ['author'], ['id'], ondelete='CASCADE')
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###
