"""Changed

Revision ID: 825353b2552c
Revises: 1d50d6070d8c
Create Date: 2023-08-01 17:44:46.603945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825353b2552c'
down_revision = '1d50d6070d8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
