"""Added Unique Constrants

Revision ID: c800bef56afa
Revises: e70267090510
Create Date: 2023-08-03 14:24:32.204586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c800bef56afa'
down_revision = 'e70267090510'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
