"""Added Library in Book

Revision ID: e70267090510
Revises: 3558b8263d4e
Create Date: 2023-08-02 18:28:23.323658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70267090510'
down_revision = '3558b8263d4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('library_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'library', ['library_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'library_id')
    # ### end Alembic commands ###
